### ISSUE TITLE
Inconsistent imports: FlagShip in SPM and Flagship in CocoaPods

### ISSUE THREAD

**Issue by harryngict** [flagship-io/flagship-ios#42]
Hi @ABTastyAdel 

I need to create a shared module that requires including FlagShip. Our shared module should support both SPM and CocoaPods. But In CocoaPods, I have to import FlagShip. However, in Package.swift for SPM, I need to import Flagship.

Please help me fix this to ensure better support

**Comment by ABTastyAdel** [comment]
Hello, @harryngict, and thank you for using the Flagship SDK. In your shared module, if it supports _**SPM and CocoaPods**_ , you can choose one of them to import the SDK, or are you trying to import them at the same time with SPM and Cocoa? 

Can you please give me a sample integration for your shared module so I can try it on my side?

Best regards
Adel.

**Comment by harryngict** [comment]
Hi @ABTastyAdel 

for example:
Cocoapods: import FlagShip
SPM: import Flagship

It will not support us to build the the library to support both SPM and cocoapods.

we expect to have the same import for from your library.

**Comment by ABTastyAdel** [comment]
Hi @harryngict , We had typo (with capital S) when first time published pod that explain collision when you use both spm and cocoa. will have a workaround to resolve this issue properly. 

_To figure out your build project_  

- Why are you importing the SDK into the same library using Cocoa and SPM ?
- Defining a visibility for the target in order to avoid conflicts is yet another option to think about. 
- Would you kindly provide me with an empty project or library that has the same configuration so I can understand your build? 

Best regards
Adel.

**Comment by ABTastyAdel** [comment]
Hi @harryngict will open a bug ticket to republish with a correct name , i 'll keep you posted.

**Comment by ABTastyAdel** [comment]
Hi @harryngict I open a bug ticket to fix the typo issue . i'll keep you  posted.
Thank you .

**Comment by harryngict** [comment]
> Hi @harryngict I open a bug ticket to fix the typo issue . i'll keep you posted. Thank you .

Thank you. 
In the meantime we did some workaround to unblock ourself.

```
#if canImport(FlagShip)
import FlagShip
#elseif canImport(Flagship)
import Flagship
#else
#error("Neither FlagShip nor Flagship can be imported")
#endif
```

**Comment by ABTastyAdel** [comment]
Hello, @harryngict Unfortunately, when I attempted to republish with the corrected typo, I received this error message. 
`[!] {"name"=>["is already taken"]}`
They have the same identifier if they are different capitalization , because they are represented on a file system and filesystems can be case-insensitive.

**Comment by ABTastyAdel** [comment]
Since renaming a pod is not possible, I close the ticket.
